### ISSUE TITLE
Error with Game of Life effect

### ISSUE THREAD

**Issue by ethanlchristensen** [ethanlchristensen/bruhanimate#40]
```py
from bruhanimate.bruhscreen import Screen
from bruhanimate.bruhrenderer import *
import bruhanimate.images as images


def game_of_life(screen):
    renderer = CenterRenderer(screen, 500, 0, images.text_to_image("Hey, Rana!"), "gol", " ", False)
    renderer.run()
    input()

Screen.show(game_of_life)
```

```bash
Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    Screen.show(game_of_life)
  File "\bruhanimate\bruhscreen.py", line 141, in show
    return function(screen)
  File "C:\Users\F4BYRF5\Desktop\Python\Jupyter\Lockhart\tmp.py", line 8, in game_of_life
    renderer.run()
  File "\bruhanimate\bruhrenderer.py", line 144, in run
    self.effect.render_frame(_) # effect buf
  File "\bruhanimate\bruheffects.py", line 412, in render_frame
    x, y, bruhcolored(self.grey_scale[current_greyscale_position], color=self.colors[current_greyscale_position]).colored)
IndexError: string index out of range
```

**Comment by ethanlchristensen** [comment]
Updating the greyscale prior to running appear to solve the issue . . . default setup must be broken
```py
    renderer.effect.update_decay(True, "GREYSCALE_r", "default")
```

**Comment by ethanlchristensen** [comment]
solved https://github.com/FNBBDevs/bruhanimate/pull/41
