### ISSUE TITLE
Line Demo + holiday demo

### ISSUE THREAD

**Issue by ethanlchristensen** [ethanlchristensen/bruhanimate#44]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ethan\Desktop\Github\bruhanimate\bruhanimate\demos\line_demo.py", line 31, in run
    Screen.show(demo, args=(image, 500, 0.05, "drawlines", " ", True))
  File "C:\Users\ethan\Desktop\Github\bruhanimate\bruhanimate\bruhscreen.py", line 138, in show
    return function(screen, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ethan\Desktop\Github\bruhanimate\bruhanimate\demos\line_demo.py", line 8, in demo
    renderer = PanRenderer(screen, frames, time, img, effect, background, transparent, loop=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ethan\Desktop\Github\bruhanimate\bruhanimate\bruhrenderer.py", line 425, in __init__
    self._set_img_attributes()
  File "C:\Users\ethan\Desktop\Github\bruhanimate\bruhanimate\bruhrenderer.py", line 432, in _set_img_attributes
    self.img_height = len(self.img)
                      ^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
```

**Comment by ethanlchristensen** [comment]
fixed: https://github.com/FNBBDevs/bruhanimate/commit/7bbd92ab24514eb2b51e5769e7bc43be3ab84146
