### ISSUE TITLE
Demos work on main PC but not on laptop . . .

### ISSUE THREAD

**Issue by ethanlchristensen** [ethanlchristensen/bruhanimate#46]
```
>>> from bruhanimate import snow_demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<User>\AppData\Roaming\Python\Python311\site-packages\bruhanimate\__init__.py", line 27, in <module>
    from bruhanimate.demos import line_demo, plasma_demo, snow_demo, holiday
ModuleNotFoundError: No module named 'bruhanimate.demos'
```

**Comment by nulzo** [comment]
ermph... this is not good...

**Comment by ethanlchristensen** [comment]
FIXED: https://github.com/FNBBDevs/bruhanimate/commit/87a950fdef082759433d81da3044c0024cbaaf9d
